Feat/cli
jananaya/iosoftware pull request #3
Opened 2024-05-28 15:30 UTC by AyenMedCa

Changes complete

2024-05-28 16:46 UTC, jananaya requested changes
Resolver comentarios

2024-05-28 16:46 UTC, jananaya commented on src/core/MatricialModelConverter.ts
> +        model.variableVector = commonVariables.concat(slackVariables, surplusVariables);
Ando refactorizando este método, pero, ¿Todo este código para que las variables estén ordenadas?, ¿Es necesario mostrarlas de esa forma?

2024-05-28 16:46 UTC, jananaya commented on src/core/ObjectiveFunction.ts
> +    variables: string[];
¿Para qué necesitamos esta propiedad?, si hacemos algo como `rsh.map(m => m.variable)` podríamos obtener las variables

2024-05-28 16:46 UTC, jananaya commented on src/core/ObjectiveFunctionValidator.ts
> +            const cleanedObjectiveFunction = objectiveFunction.replace(/\s+/g, '').trim();
Esto no se debería hacer en este método, sino en main.ts al momento de recibir la entrada del usuario desde el teclado

2024-05-28 16:46 UTC, jananaya commented on src/core/RestrictionValidator.ts
> +        const cleanedRestriction = restriction.replace(/\s+/g, '').trim();
Mismo comentario, del otro validador, este método no es responsable de limpiar la entrada, solo verifica que lo que le llegue sea válido

2024-05-28 16:46 UTC, jananaya commented on src/core/ObjetiveFunctionNormalizer.ts
> +import ObjectiveFunction from './ObjectiveFunction';
Un mejor nombre para esta clase sería ObjectiveFunctionMaximizer

2024-05-28 16:46 UTC, jananaya commented on src/core/ObjetiveFunctionNormalizer.ts
> +    static normalize(objectiveFunction: ObjectiveFunction): ObjectiveFunction {
maximize

2024-06-02 02:17 UTC, AyenMedCa commented on src/core/InputCleaner.ts
Se añadio el limpiador como una clase aparte y se implemento en el main

2024-06-02 02:17 UTC, AyenMedCa commented on src/cli/main.ts
> +        objectiveFunction = InputCleaner.clean(await getInput("Ingrese la función objetivo: "));
Aqui esta implementado

2024-06-02 02:18 UTC, AyenMedCa commented on src/core/Monomial.ts
> -};
Se elimino la variable que guardaba las variables de la funcion objetivo

2024-06-02 02:21 UTC, AyenMedCa commented on src/core/RestrictionValidator.ts
> +        objectiveFunction.rhs.forEach(monomial => objectiveVariables.push(`${'x'}${monomial.variable}`));
Haciendo entonces que RestrictionValidator.ts reciba el objeto de la funcion, saque las variables y las guarde en un array para comprobarlo

2024-06-02 02:31 UTC, merged

2024-06-02 02:34 UTC, valenboc commented on src/cli/main.ts
si